### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by sepandhaghighi** [openscilab/nava#12]
#### Description
Add CLI options

```shell
nava alarm.wav
```

```shell
nava --file="alarm.wav"
```

**Comment by lewoudar** [comment]
FWIW, I created a small command line interface after reading this issue :)
https://github.com/lewoudar/son

**Comment by sadrasabouri** [comment]
> FWIW, I created a small command line interface after reading this issue :) https://github.com/lewoudar/son

Hey Kevin, that's so cool. Thanks for sharing your package with us. I saw Pomodoro action in your programs list. You may want to check our other project my timer:
[https://github.com/sepandhaghighi/mytimer](https://github.com/sepandhaghighi/mytimer)

**Comment by lewoudar** [comment]
> Hey Kevin, that's so cool. Thanks for sharing your package with us. I saw Pomodoro action in your programs list. You may want to check our other project my timer:
https://github.com/sepandhaghighi/mytimer

Hi @sadrasabouri, thank you for pointing me this project, I will check it when I have some free time :)
