### ISSUE TITLE
Decorator hides parameter

### ISSUE THREAD

**Issue by sepandhaghighi** [openscilab/nava#16]
#### Description
The decorator hides the parameters of the function
![image](https://github.com/openscilab/nava/assets/7515099/f947136c-0a73-4efe-a40f-a096eedc9c58)

#### Operating System
Windows 10
#### Python Version
Python 3.8
#### nava Version (Use : `nava.__version__`)
Nava 0.1

We should use `@wraps` from `functools` module like [here](https://github.com/sepandhaghighi/pycm/blob/a163c07fb23fd5384f4a6049afa16241954f6545/pycm/pycm_util.py#L786)

**Comment by sadrasabouri** [comment]
Although this is not an issue in VSCode using Python extension. Parameter suggestion working OK there.
BTW, I will work on this issue to fix it in Python interpreter.
