### ISSUE TITLE
Decorator issue with keyword arguments

### ISSUE THREAD

**Issue by sepandhaghighi** [openscilab/nava#17]
#### Description
Decorators cannot handle keyword arguments
#### Steps/Code to Reproduce
```pycon
>>> from nava import play
>>> play(sound_path="alarm.wav")
```
#### Expected Behavior
Play sound
#### Actual Behavior
```shell
Traceback (most recent call last):
    ...
IndexError: tuple index out of range
```
#### Operating System
Windows 10
#### Python Version
Python 3.8
#### nava Version (Use : `nava.__version__`)
Nava 0.1

**Comment by sadrasabouri** [comment]
Hey @AHReccese 
Since we handled the decorator manipulating `args` only, keyword arguments' use-cases are not covered now. I have assigned you to this issue to handle it anytime you can before nava v0.2 release.
Please let us know if you are not free for this task so that I would re-assign it.
