### ISSUE TITLE
Support async mode

### ISSUE THREAD

**Issue by sepandhaghighi** [openscilab/nava#5]
#### Description
Support async mode

**Comment by sadrasabouri** [comment]
@NimaSamadi007 Now it's time for you to open the pull request to the `dev` branch.
note: we decided to handle `async` first and then add the `loop` feature as a standalone feature for the future release.
Thank you.

**Comment by NimaSamadi007** [comment]
Sure. I will create a PR by tonight and also remove the loop feature.
